apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hope-country-report.fullname" . }}
  labels:
    {{- include "hope-country-report.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value :=  .Values.secret }}
{{- if eq "bool" (typeOf $value) }}
{{- $stringValue := $value | toString }}
  {{ $key }}: {{ $stringValue | b64enc | quote }}
{{- else }}
  {{- if eq $value "" }}
  {{- else }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
