# Generated by Django 4.2.7 on 2023-11-07 09:07

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hope_country_report.apps.power_query.json
import hope_country_report.apps.power_query.models._base
import hope_country_report.apps.power_query.models.arguments
import strategy_field.fields
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formatter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.TextField(blank=True, null=True)),
                (
                    "file_suffix",
                    models.CharField(
                        choices=[
                            (".json", "application/json"),
                            (".pdf", "application/pdf"),
                            (".xls", "application/vnd.ms-excel"),
                            (".zip", "application/x-zip-compressed"),
                            (".png", "image/png"),
                            (".csv", "text/csv"),
                            (".html", "text/html"),
                            (".txt", "text/plain"),
                            (".xml", "text/xml"),
                            (".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
                            (".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
                            (".yaml", "text/vnd.yaml"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "processor",
                    strategy_field.fields.StrategyField(
                        default="hope_country_report.apps.power_query.processors.ToHTML"
                    ),
                ),
                ("type", models.IntegerField(choices=[(1, "List"), (2, "Detail")], default=1)),
                ("compress", models.BooleanField(blank=True, default=False)),
                (
                    "country_office",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.countryoffice"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parametrizer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(editable=False, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "value",
                    models.JSONField(
                        default=dict,
                        validators=[hope_country_report.apps.power_query.models.arguments.validate_queryargs],
                    ),
                ),
                ("system", models.BooleanField(blank=True, default=False, editable=False)),
                (
                    "country_office",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.countryoffice"
                    ),
                ),
            ],
            options={
                "verbose_name": "Arguments",
                "verbose_name_plural": "Arguments",
            },
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number")),
                ("sentry_error_id", models.CharField(blank=True, max_length=400, null=True)),
                ("error_message", models.CharField(blank=True, max_length=400, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "curr_async_result_id",
                    models.CharField(blank=True, help_text="Current (active) AsyncResult is", max_length=36, null=True),
                ),
                (
                    "last_async_result_id",
                    models.CharField(blank=True, help_text="Latest executed AsyncResult is", max_length=36, null=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("code", models.TextField(blank=True, default="result=conn.all()")),
                (
                    "info",
                    models.JSONField(
                        blank=True, default=dict, encoder=hope_country_report.apps.power_query.json.PQJSONEncoder
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "country_office",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.countryoffice"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parametrizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="power_query.parametrizer",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="power_query.query"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name_plural": "Queries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ReportConfiguration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number")),
                ("sentry_error_id", models.CharField(blank=True, max_length=400, null=True)),
                ("error_message", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "curr_async_result_id",
                    models.CharField(blank=True, help_text="Current (active) AsyncResult is", max_length=36, null=True),
                ),
                (
                    "last_async_result_id",
                    models.CharField(blank=True, help_text="Latest executed AsyncResult is", max_length=36, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Report Title")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, default="", max_length=255, null=True)),
                ("active", models.BooleanField(default=True)),
                ("visible", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=hope_country_report.apps.power_query.json.PQJSONEncoder,
                        help_text="Extra to add to the report context",
                    ),
                ),
                ("compress", models.BooleanField(blank=True, default=False, help_text="Compress reports with Zip")),
                (
                    "protect",
                    models.BooleanField(
                        blank=True, default=False, help_text="Protect zip file with system generated password"
                    ),
                ),
                (
                    "pwd",
                    models.CharField(
                        blank=True, editable=False, help_text="Auto generated password to protect .zip files", null=True
                    ),
                ),
                (
                    "country_office",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.countryoffice"
                    ),
                ),
                ("formatters", models.ManyToManyField(to="power_query.formatter")),
                (
                    "limit_access_to",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit access to selected users",
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notify_to",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users to be notified when report have been created/updated",
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("query", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="power_query.query")),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="django_celery_beat.periodictask",
                        verbose_name="Scheduling",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("doc", models.FileField(upload_to="")),
                ("file_suffix", models.CharField(max_length=20)),
                (
                    "country_office",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.countryoffice"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="parametrizer",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="power_query.query",
            ),
        ),
        migrations.AddField(
            model_name="formatter",
            name="template",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="power_query.reporttemplate"
            ),
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=hope_country_report.apps.power_query.models._base.FileProviderMixin.get_file_path,
                    ),
                ),
                ("size", models.IntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("hash", models.CharField(editable=False, max_length=200, unique=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("description", models.CharField(max_length=100)),
                ("info", models.JSONField(blank=True, default=dict)),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="datasets", to="power_query.query"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportDocument",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=hope_country_report.apps.power_query.models._base.FileProviderMixin.get_file_path,
                    ),
                ),
                ("size", models.IntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                (
                    "arguments",
                    models.JSONField(default=dict, encoder=hope_country_report.apps.power_query.json.PQJSONEncoder),
                ),
                ("info", models.JSONField(blank=True, default=dict)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="power_query.dataset"
                    ),
                ),
                (
                    "formatter",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="power_query.formatter"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="power_query.reportconfiguration",
                    ),
                ),
            ],
            options={
                "permissions": (("download_reportdocument", "Can download Document"),),
                "unique_together": {("report", "dataset", "formatter")},
            },
        ),
    ]
