# Generated by Django 4.2.7 on 2024-01-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_query", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="error_message",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="query",
            name="sentry_error_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="error_message",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="sentry_error_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
