# Generated by Django 4.2.7 on 2024-01-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_query", "0002_alter_query_error_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
