# Generated by Django 4.2.10 on 2024-02-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_query", "0003_alter_query_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formatter",
            name="item_per_page",
            field=models.SmallIntegerField(default=0),
        ),
    ]
