# Generated by Django 4.2.10 on 2024-02-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("power_query", "0004_formatter_item_per_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="code",
            field=models.TextField(blank=True, default="result=conn.all()", null=True),
        ),
        migrations.AlterField(
            model_name="query",
            name="target",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
            ),
        ),
    ]
