# Generated by Django 4.2.10 on 2024-02-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_query", "0005_alter_query_code_alter_query_target_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="query",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("code__isnull", True),
                        ("country_office__isnull", False),
                        ("parent__isnull", False),
                        ("target__isnull", True),
                    ),
                    models.Q(("code__isnull", False), ("parent__isnull", True), ("target__isnull", False)),
                    _connector="OR",
                ),
                name="valid_query",
            ),
        ),
    ]
