# Generated by Django 5.0.4 on 2024-08-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_query", "0006_query_valid_query"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parametrizer",
            options={"ordering": ["name"], "verbose_name": "Arguments", "verbose_name_plural": "Arguments"},
        ),
        migrations.RemoveField(
            model_name="chartpage",
            name="datasource",
        ),
        migrations.AlterField(
            model_name="chartpage",
            name="template",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="power_query.reporttemplate"
            ),
        ),
    ]
