# Generated by Django 5.0.4 on 2024-08-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("power_query", "0007_alter_parametrizer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formatter",
            name="file_suffix",
            field=models.CharField(
                choices=[
                    (".json", "application/json"),
                    (".pdf", "application/pdf"),
                    (".xls", "application/vnd.ms-excel"),
                    (".zip", "application/x-zip-compressed"),
                    (".png", "image/png"),
                    (".csv", "text/csv"),
                    (".html", "text/html"),
                    (".txt", "text/plain"),
                    (".xml", "text/xml"),
                    (".yaml", "text/vnd.yaml"),
                    (".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
                ],
                max_length=10,
            ),
        ),
    ]
