# Generated by Django 5.1.7 on 2025-04-10 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_query", "0009_alter_formatter_file_suffix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportconfiguration",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "queue",
                    "terminate",
                    "inspect",
                    "revoke",
                )
            },
        ),
        migrations.AddField(
            model_name="query",
            name="celery_history",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="query",
            name="datetime_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Creation date and time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="query",
            name="datetime_queued",
            field=models.DateTimeField(
                blank=True,
                help_text="Queueing date and time",
                null=True,
                verbose_name="Queued At",
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="group_key",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Tasks with the same group key will not run in parallel",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="local_status",
            field=models.CharField(blank=True, default="", editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="query",
            name="repeatable",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indicate if the job can be repeated as-is",
            ),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="celery_history",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="datetime_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Creation date and time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="datetime_queued",
            field=models.DateTimeField(
                blank=True,
                help_text="Queueing date and time",
                null=True,
                verbose_name="Queued At",
            ),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="group_key",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Tasks with the same group key will not run in parallel",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="local_status",
            field=models.CharField(blank=True, default="", editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="repeatable",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indicate if the job can be repeated as-is",
            ),
        ),
        migrations.RenameField(
            model_name="query",
            old_name="curr_async_result_id",
            new_name="task_id",
        ),
        migrations.RemoveField(
            model_name="query",
            name="last_async_result_id",
        ),
        migrations.RenameField(
            model_name="reportconfiguration",
            old_name="curr_async_result_id",
            new_name="task_id",
        ),
        migrations.RemoveField(
            model_name="reportconfiguration",
            name="last_async_result_id",
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="pwd",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto generated password to protect .zip files",
                max_length=257,
                null=True,
            ),
        ),
    ]
