# Generated by Django 5.1.7 on 2025-04-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_query", "0010_alter_reportconfiguration_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="query",
            name="task_id",
        ),
        migrations.RemoveField(
            model_name="reportconfiguration",
            name="task_id",
        ),
        migrations.AddField(
            model_name="query",
            name="curr_async_result_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Current (active) AsyncResult is",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="last_async_result_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Latest executed AsyncResult is",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="curr_async_result_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Current (active) AsyncResult is",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="last_async_result_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Latest executed AsyncResult is",
                max_length=36,
                null=True,
            ),
        ),
    ]
