# Generated by Django 5.2.15 on 2026-06-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_query", "0011_remove_query_task_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formatter",
            name="file_suffix",
            field=models.CharField(
                choices=[
                    (".json", "application/json"),
                    (".pdf", "application/pdf"),
                    (".xls", "application/vnd.ms-excel"),
                    (".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
                    (".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
                    (".yaml", "text/vnd.yaml"),
                    (".zip", "application/x-zip-compressed"),
                    (".png", "image/png"),
                    (".csv", "text/csv"),
                    (".html", "text/html"),
                    (".txt", "text/plain"),
                    (".xml", "text/xml"),
                ],
                max_length=10,
            ),
        ),
    ]
