# Generated by Django 6.0.8 on 2026-10-08 15:10

import hope_country_report.apps.power_query.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_query", "0012_alter_formatter_file_suffix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporttemplate",
            name="doc",
            field=models.FileField(
                upload_to=hope_country_report.apps.power_query.validators.report_template_upload_to,
                validators=[
                    hope_country_report.apps.power_query.validators.validate_template_extension,
                    hope_country_report.apps.power_query.validators.validate_template_size,
                    hope_country_report.apps.power_query.validators.validate_template_content,
                ],
            ),
        ),
    ]
