# Generated by Django 4.2.5 on 2023-09-15 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import power_query.json
import power_query.models
import power_query.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.POWER_QUERY_PROJECT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "swappable": "POWER_QUERY_PROJECT_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Formatter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("csv", "text/csv"),
                            ("html", "text/html"),
                            ("json", "application/json"),
                            ("txt", "text/plain"),
                            ("xls", "application/vnd.ms-excel"),
                            ("xml", "application/xml"),
                            ("yaml", "text/yaml"),
                        ],
                        max_length=5,
                    ),
                ),
                ("code", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Parametrizer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(editable=False, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, max_length=255, null=True)),
                ("value", models.JSONField(default=dict, validators=[power_query.models.validate_queryargs])),
                ("system", models.BooleanField(blank=True, default=False, editable=False)),
            ],
            options={
                "verbose_name": "Arguments",
                "verbose_name_plural": "Arguments",
            },
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("celery_task", models.CharField(blank=True, max_length=36, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("code", models.TextField(blank=True, default="qs=conn.all()")),
                ("info", models.JSONField(blank=True, default=dict, encoder=power_query.json.PQJSONEncoder)),
                ("sentry_error_id", models.CharField(blank=True, max_length=400, null=True)),
                ("error_message", models.CharField(blank=True, max_length=400, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parametrizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="power_query.parametrizer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.POWER_QUERY_PROJECT_MODEL
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name_plural": "Power Queries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("celery_task", models.CharField(blank=True, max_length=36, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("document_title", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "frequence",
                    models.CharField(
                        blank=True,
                        default="mon,tue,wed,thu,fri,sat,sun",
                        help_text="Refresh every (e.g. 3 - 1/3 - mon - 1/3,Mon)",
                        max_length=30,
                        null=True,
                        validators=[power_query.validators.FrequencyValidator()],
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("validity_days", models.IntegerField(default=365)),
                (
                    "formatter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="power_query.formatter"),
                ),
                ("limit_access_to", models.ManyToManyField(blank=True, related_name="+", to=settings.AUTH_USER_MODEL)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("query", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="power_query.query")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="parametrizer",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="power_query.query",
            ),
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hash", models.CharField(editable=False, max_length=200, unique=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("description", models.CharField(max_length=100)),
                ("value", models.BinaryField(blank=True, null=True)),
                ("info", models.JSONField(blank=True, default=dict)),
                (
                    "extra",
                    models.BinaryField(blank=True, help_text="Any other attribute to pass to the formatter", null=True),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="datasets", to="power_query.query"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportDocument",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("output", models.BinaryField(blank=True, null=True)),
                ("arguments", models.JSONField(default=dict, encoder=power_query.json.PQJSONEncoder)),
                ("content_type", models.CharField(choices=[], max_length=5)),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="power_query.dataset")),
                ("limit_access_to", models.ManyToManyField(blank=True, related_name="+", to=settings.AUTH_USER_MODEL)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="power_query.report"
                    ),
                ),
            ],
            options={
                "unique_together": {("report", "dataset")},
            },
        ),
    ]
