version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: tests
    environment:
      - SECRET_KEY=secret-key
      - DATABASE_URL=postgis://postgres:postgres@db:5432/postgres
      - DATABASE_HOPE_URL=postgis://postgres:postgres@db:5432/postgres
      - CACHE_URL=redis://redis:6379/2
      - CELERY_BROKER_URL=redis://redis:6379/3
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./~build/:/code/~build
  db:
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      start_period: 5s
      interval: 5s
      timeout: 4s
      retries: 5

  redis:
    image: redis:7.2
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 5s
      interval: 5s
      timeout: 4s
      retries: 5
