version: '3.8'

volumes:
  postgres_data:

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    command: run
    environment:
      - SECRET_KEY=secret-key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hcr
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 8000:8000
    volumes:
      - .:/code
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hcr
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      start_period: 5s
      interval: 5s
      timeout: 4s
      retries: 5

  redis:
    image: redis:7.2
    ports:
      - 6379:6379
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 5s
      interval: 5s
      timeout: 4s
      retries: 5