# Generated by Django 5.2.4 on 2025-09-30 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_alter_user_time_format"),
        ("power_query", "0011_remove_query_task_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("enabled", models.BooleanField(blank=True, default=True)),
                ("extras", models.JSONField(blank=True, default=dict)),
                (
                    "office",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.countryoffice"
                    ),
                ),
                (
                    "query",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="power_query.query"
                    ),
                ),
            ],
        ),
    ]
