# Generated by Django 5.2.7 on 2025-10-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="routing_key",
            field=models.CharField(default="hcr.dataset.save", max_length=255),
        ),
    ]
