# Generated by Django 5.2.7 on 2025-11-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0002_event_routing_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="publish_as_url",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="If true, event will contain a URL to the dataset instead of the data",
            ),
        ),
    ]
