# Generated by Django 5.2.15 on 2026-06-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0003_event_publish_as_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="routing_key",
            field=models.CharField(blank=True, default="hcr.dataset.save", max_length=255),
        ),
    ]
