import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models

import timezone_field.fields
import unicef_security.models

# Generated by Django 4.2.7 on 2023-11-15 13:33


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("azure_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                ("display_name", models.CharField(blank=True, max_length=100, null=True)),
                ("timezone", timezone_field.fields.TimeZoneField(default="UTC", verbose_name="Timezone")),
                (
                    "language",
                    models.CharField(
                        choices=[("es", "Spanish"), ("fr", "French"), ("en", "English"), ("ar", "Arabic")],
                        default="en",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("Y M d", "2000 Dec 31"),
                            ("j M Y", "31 Dec 2000"),
                            ("Y-m-d", "2000-12-31"),
                            ("Y M d, l", "2000 Dec 31, Sunday"),
                            ("D, j M Y", "Sun, 31 Dec 2000"),
                        ],
                        default="Y M d",
                        help_text="Only applied to user interface. It will not be applied to the reports",
                        max_length=20,
                        verbose_name="Date Format",
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[("h:i a", "11:59 p.m."), ("H:i", "23:59")],
                        default="h:i a",
                        help_text="Only applied to user interface. It will not be applied to the reports",
                        max_length=20,
                        verbose_name="Date Format",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "permissions": (("access_api", "Can access API"),),
                "swappable": "AUTH_USER_MODEL",
            },
            bases=(unicef_security.models.TimeStampedModel, models.Model),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CountryShape",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("area", models.IntegerField(blank=True, null=True)),
                ("fips", models.CharField(max_length=2, null=True, verbose_name="FIPS Code")),
                ("iso2", models.CharField(blank=True, max_length=2, null=True, verbose_name="2 Digit ISO")),
                ("iso3", models.CharField(blank=True, max_length=3, null=True, verbose_name="3 Digit ISO")),
                ("un", models.IntegerField(blank=True, null=True, verbose_name="United Nations Code")),
                ("region", models.IntegerField(blank=True, null=True, verbose_name="Region Code")),
                ("subregion", models.IntegerField(blank=True, null=True, verbose_name="Sub-Region Code")),
                ("lon", models.FloatField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("mpoly", django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(unicef_security.models.TimeStampedModel, models.Model),
        ),
        migrations.CreateModel(
            name="CountryOffice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=100)),
                ("active", models.BooleanField(blank=True, default=False)),
                ("code", models.CharField(blank=True, max_length=10, unique=True)),
                ("long_name", models.CharField(blank=True, max_length=255)),
                ("region_code", models.CharField(blank=True, max_length=8)),
                ("region_name", models.CharField(blank=True, max_length=8)),
                ("hope_id", models.CharField(blank=True, max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(
                        default="UTC", help_text="Country default timezone.", verbose_name="Timezone"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("es", "Spanish"), ("fr", "French"), ("en", "English"), ("ar", "Arabic")],
                        default="en",
                        help_text="Country default locale. It affects dates and number formats",
                        max_length=10,
                        verbose_name="Locale",
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "shape",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.countryshape"
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(unicef_security.models.TimeStampedModel, models.Model),
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expires", models.DateField(blank=True, null=True)),
                (
                    "country_office",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.countryoffice"),
                ),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.group")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="roles", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "group", "country_office")},
            },
            bases=(unicef_security.models.TimeStampedModel, models.Model),
        ),
    ]
