# Generated by Django 4.2.7 on 2023-11-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="time_format",
            field=models.CharField(
                choices=[("h:i a", "11:59 p.m."), ("H:i", "23:59")],
                default="h:i a",
                help_text="Only applied to user interface. It will not be applied to the reports",
                max_length=20,
                verbose_name="Time Format",
            ),
        ),
    ]
