# Generated by Django 4.2.1 on 2023-05-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("withdrawn", models.BooleanField(db_index=True, default=False)),
                ("withdrawn_date", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
