# Generated by Django 4.2.1 on 2023-05-31 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hope", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="household",
            table="household_household",
        ),
    ]
