from ..settings import env

AZURE_OVERWRITE_FILES = True
AZURE_ACCOUNT_NAME = env("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY = env("AZURE_ACCOUNT_KEY")
AZURE_CONTAINER = env("AZURE_CONTAINER")

HOPE_AZURE_ACCOUNT_NAME = env("HOPE_AZURE_ACCOUNT_NAME")
HOPE_AZURE_ACCOUNT_KEY = env("HOPE_AZURE_ACCOUNT_KEY")
HOPE_AZURE_AZURE_CONTAINER = env("HOPE_AZURE_AZURE_CONTAINER")
HOPE_AZURE_SAS_TOKEN = env("HOPE_AZURE_SAS_TOKEN")

MEDIA_AZURE_ACCOUNT_NAME = env("MEDIA_AZURE_ACCOUNT_NAME")
MEDIA_AZURE_ACCOUNT_KEY = env("MEDIA_AZURE_ACCOUNT_KEY")
MEDIA_AZURE_AZURE_CONTAINER = env("MEDIA_AZURE_AZURE_CONTAINER")
MEDIA_AZURE_SAS_TOKEN = env("MEDIA_AZURE_SAS_TOKEN")
