name: "Documentation"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - develop
      - mastetr
  schedule:
    - cron: '37 23 * * 2'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install mkDocs
        run: |
          sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          pip install uv
          uv sync --dev
          uv run mkdocs build -d ./docs-output
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs-output

  # Deployment job
  deploy:
    if: contains(github.ref, 'develop')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
