name: SDLC - Develop push

on:
  push:
    branches:
      - develop

jobs:
  build-push-develop:
    name: "Build & push image"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push develop image
        run: |
          IMAGE_TAG="develop"
          docker buildx create --use
          docker buildx build \
            --cache-from ${{ vars.DOCKERHUB_ORGANIZATION }}/${{ vars.DOCKERHUB_REPOSITORY }}:cache-$IMAGE_TAG-dist \
            --cache-to ${{ vars.DOCKERHUB_ORGANIZATION }}/${{ vars.DOCKERHUB_REPOSITORY }}:cache-$IMAGE_TAG-dist \
            -t ${{ vars.DOCKERHUB_ORGANIZATION }}/${{ vars.DOCKERHUB_REPOSITORY }}:$IMAGE_TAG-dist \
            -f ./Dockerfile \
            --push \
            ./

  deploy:
    name: "Trigger deployment"
    needs: [build-push-develop]
    uses: ./.github/workflows/trigger-azure-pipeline.yml
    with:
      azure-organization: ${{ vars.AZURE_ORGANIZATION }}
      azure-project: ${{ vars.AZURE_PROJECT }}
      azure-pipeline-id: 1634
    secrets:
      azure-pat: ${{ secrets.AZURE_PAT }}