name: SDLC - Other branches push

on:
  push:
    branches-ignore:
      - develop
      - uat/**
      - stable/**

jobs:
  prepare-docker:
    name: "Prepare Docker image tag"
    runs-on: ubuntu-latest
    outputs:
      docker_image_tag: ${{ steps.sanitize-branch.outputs.docker_image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current branch name
        id: get-branch
        run: |
          if [[ "${GITHUB_REF}" == refs/pull/*/merge ]]; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          else
            BRANCH_NAME="${GITHUB_REF##*/}"
          fi
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Sanitize branch name for Docker
        id: sanitize-branch
        run: |
          SAFE_BRANCH=$(echo "${{ steps.get-branch.outputs.branch_name }}" | tr '[:upper:]' '[:lower:]' | sed 's#[^a-z0-9_.-]#-#g')
          echo "docker_image_tag=$SAFE_BRANCH" >> $GITHUB_OUTPUT

  build-push:
    name: "Build & push image"
    runs-on: ubuntu-latest
    needs: [prepare-docker]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE_TAG="${{ needs.prepare-docker.outputs.docker_image_tag }}"
          docker buildx create --use
          docker buildx build \
            --cache-from ${{ vars.DOCKERHUB_ORGANIZATION }}/${{ var.DOCKERHUB_REPOSITORY }}:cache-develop-dist \
            --cache-from ${{ vars.DOCKERHUB_ORGANIZATION }}/${{ var.DOCKERHUB_REPOSITORY }}:cache-$IMAGE_TAG-dist \
            --cache-to ${{ vars.DOCKERHUB_ORGANIZATION }}/${{ var.DOCKERHUB_REPOSITORY }}:cache-$IMAGE_TAG-dist \
            -t ${{ vars.DOCKERHUB_ORGANIZATION }}/${{ var.DOCKERHUB_REPOSITORY }}:$IMAGE_TAG-dist \
            -f ./Dockerfile \
            --push \
            ./
